### ISSUE TITLE
Installation on Ubuntu nad nodejs 14.16 unsupported

### ISSUE THREAD

**Issue by jonkiszp** [felixbrucker/foxy-proxy#1186]
`npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/bhd-burst-proxy -> /usr/lib/node_modules/foxy-proxy/main.js
/usr/bin/foxy-proxy -> /usr/lib/node_modules/foxy-proxy/main.js

> sqlite3@5.0.2 install /usr/lib/node_modules/foxy-proxy/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@14.16.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 5.4.0-70-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /usr/lib/node_modules/foxy-proxy/node_modules/sqlite3
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/foxy-proxy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-70-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/foxy-proxy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/foxy-proxy/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN notsup Unsupported engine for foxy-proxy@1.39.0: wanted: {"node":"^10.12 || ^12"} (current: {"node":"14.16.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: foxy-proxy@1.39.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-08T10_43_20_458Z-debug.log
`

**Comment by felixbrucker** [comment]
Hey, it looks like you are installing foxy-proxy as a regular user using the system provided nodejs. This is not recommended because you run into all sorts of issues like these. In your case the native module for sqlite cant be written/accesses because its in a global directory: `Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/foxy-proxy/node_modules/sqlite3/.node-gyp'`

Instead please remove nodejs and npm from your system and use `nvm` to manage nodejs versions instead: https://docs.foxypool.io/general/installing-nodejs/

**Comment by jonkiszp** [comment]
I installed node.js via nvm but still has an error.

`npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/home/jonkiszp/.nvm/versions/node/v14.16.1/bin/bhd-burst-proxy -> /home/jonkiszp/.nvm/versions/node/v14.16.1/lib/node_modules/foxy-proxy/main.js
/home/jonkiszp/.nvm/versions/node/v14.16.1/bin/foxy-proxy -> /home/jonkiszp/.nvm/versions/node/v14.16.1/lib/node_modules/foxy-proxy/main.js

> sqlite3@5.0.2 install /home/jonkiszp/.nvm/versions/node/v14.16.1/lib/node_modules/foxy-proxy/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/home/jonkiszp/.nvm/versions/node/v14.16.1/lib/node_modules/foxy-proxy/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
npm WARN notsup Unsupported engine for foxy-proxy@1.39.0: wanted: {"node":"^10.12 || ^12"} (current: {"node":"14.16.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: foxy-proxy@1.39.0
`

**Comment by felixbrucker** [comment]
Yes, those seem to be only warnings because foxy-proxy is not officially compatible with node 14, but should probbaly work fine.

**Comment by jonkiszp** [comment]
Ok thank for help.
