### ISSUE TITLE
"Latest Blocks won" explorer url

### ISSUE THREAD

**Issue by locknum** [felixbrucker/foxy-proxy#340]
The Last Blocks won card's url for BlockHeight defaults to BHD (https://www.btchd.org/explorer/block/xxxxxx) regardless of the chain that is being mined. Burst wins on Foxy-Pool are incorrectly pointing to the BHD explorer.

Issue found on 1.26.0

**Comment by felixbrucker** [comment]
For Burst set `isBHD` to false to fix this. For other coins this will be fixed with a future update.

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/foxy-proxy/commit/32c1ef4c366e0678137b093fc2f8cd8449a7204f
