### ISSUE TITLE
Boom agent

### ISSUE THREAD

**Issue by wy414012** [felixbrucker/foxy-proxy#370]
When can you increase the boom agent mining that supports B3pool onepool?

**Comment by felixbrucker** [comment]
Can you elaborate? Which error do you get?

**Comment by wy414012** [comment]
@felixbrucker unable to connect  Direct disconnect

**Comment by wy414012** [comment]
@felixbrucker  2019-08-01 12:45:28.816 [ERROR] | disc | one BOOM | Connection outage detected ..

**Comment by wy414012** [comment]
@felixbrucker  The configuration is as follows:     
  - name: 'one BOOM'
        mode: pool
        url: 'http://ecoboom.pool.onepool.co'
        accountName: 'ymwl03'
        coin: BOOM
        targetDL: 31536000
        weight: 9

**Comment by felixbrucker** [comment]
Please ask generic mining related question in our [Discord](https://discord.gg/gNHhn9y).

From a quick look it seems like onepool requires you to send your account key, so you should probably add that to your config. In doubt ask the onepool staff/support what else they require.

Closing here as this is not a feature.

**Comment by wy414012** [comment]
@felixbrucker  Already consulted, and do not need to send the account private key, the BlagoMiner 80 port is directly connected.   I am in a discussion group, it is too much trouble, I can't connect directly, so I can only consult you here.
