### ISSUE TITLE
Display targetDL from submitProbability

### ISSUE THREAD

**Issue by pokermaster100** [felixbrucker/foxy-proxy#409]
**Is your feature request related to a problem? Please describe.**
Not able to view dynamic targetDL used with submitProbability (especially while using "sendTargetDL")

**Describe the solution you'd like**
Add a line for target DL under the difficulty on the webui of the proxy.

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/foxy-proxy/commit/c125d901af0090bd70c3afd14f96efbb8591b185
