### ISSUE TITLE
Error: connect ECONNREFUSED :::443

### ISSUE THREAD

**Issue by benthetechguy** [felixbrucker/foxy-proxy#847]
I recently installed the latest version of foxy-proxy, and every couple seconds I get this error:
`Error: connect ECONNREFUSED :::443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::',
  port: 443
}`
Everything seems to be working fine as far as i can tell, so i'm curious about what this error is and what is causing it. I have my config.yaml below.
[config.yaml.txt](https://github.com/felixbrucker/foxy-proxy/files/4874490/config.yaml.txt) (it's a .txt file because github doesn't support uploading .yaml files)

**Comment by felixbrucker** [comment]
Do you have any system wide dns overrides in place, like pi-hole etc?
The upstreams in your setup do not use https, so it can be only one of three things:
- Checking for the latest version: `https://api.github.com`
- Reporting exceptions to sentry; `https://sentry.io`
- Reporting telemetry to google analytics: `https://www.google-analytics.com`

Can you verify all domains are reachable just fine?

**Comment by benthetechguy** [comment]
Ah, it was the google analytics. That's in my pi-hole blacklist by default.
I'll add it to my whitelist. Thanks for the quick and effective response!

**Comment by felixbrucker** [comment]
You can also disable them via the config option `disableAnonymousStatistics: true`

**Comment by benthetechguy** [comment]
Ok I will do that instead because that way i don't have to modify the pi-hole. Thank you for your help!
