### ISSUE TITLE
Ubuntu 20.04: Error: Please install sqlite3 package manually

### ISSUE THREAD

**Issue by jacobianb** [felixbrucker/foxy-proxy#907]
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
    at new Sequelize (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/sequelize.js:340:20)
    at init (/usr/local/lib/node_modules/foxy-proxy/models/index.js:40:21)
    at module.exports (/usr/local/lib/node_modules/foxy-proxy/models/index.js:75:5)
    at /usr/local/lib/node_modules/foxy-proxy/app.js:104:9
    at Object.<anonymous> (/usr/local/lib/node_modules/foxy-proxy/app.js:278:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-08-03 14:31:46.052 [ERROR] | Error: Please install sqlite3 package manually
```

Steps to reproduce:
Fresh Lubuntu 20.04 Install
```
apt install npm
npm i -g foxy-proxy
foxy-proxy
```

Manually installing sqlite3 does not solve the problem.

I am able to use foxy-proxy fine if I use the github installation instructions, however.

**Comment by felixbrucker** [comment]
I suspect your sqlite build fails, can you verify when running `npm i -g foxy-proxy` no errors are shown? You might need build-essential (or the equiv) installed for building.

Additionally i can recommend using nvm to install node on linux, instead of apt, so that you have control over which node version you use.

**Comment by jacobianb** [comment]
root@jake-linuxvm:~# npm i -g foxy-proxy
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/bhd-burst-proxy -> /usr/local/lib/node_modules/foxy-proxy/main.js
/usr/local/bin/foxy-proxy -> /usr/local/lib/node_modules/foxy-proxy/main.js
npm WARN notsup Unsupported engine for bitmart-api@1.2.0: wanted: {"node":"^12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: bitmart-api@1.2.0

+ foxy-proxy@1.36.3
updated 1 package in 11.8s

**Comment by felixbrucker** [comment]
> updated 1 package in 11.8s

Please remove the package before installing again, you can do so via `npm uninstall -g foxy-proxy`

**Comment by jacobianb** [comment]
root@jake-linuxvm:~# npm uninstall -g foxy-proxy
removed 329 packages in 2.439s
root@jake-linuxvm:~# npm i -g foxy-proxy
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/bhd-burst-proxy -> /usr/local/lib/node_modules/foxy-proxy/main.js
/usr/local/bin/foxy-proxy -> /usr/local/lib/node_modules/foxy-proxy/main.js

> sqlite3@5.0.0 install /usr/local/lib/node_modules/foxy-proxy/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build


root@jake-linuxvm:~# foxy-proxy
 ______  ______   __  __   __  __       ______  ______   ______   __  __   __  __
/\  ___\/\  __ \ /\_\_\_\ /\ \_\ \     /\  == \/\  == \ /\  __ \ /\_\_\_\ /\ \_\ \
\ \  __\\ \ \/\ \\/_/\_\/_\ \____ \    \ \  _-/\ \  __< \ \ \/\ \\/_/\_\/_\ \____ \
 \ \_\   \ \_____\ /\_\/\_\\/\_____\    \ \_\   \ \_\ \_\\ \_____\ /\_\/\_\\/\_____\
  \/_/    \/_____/ \/_/\/_/ \/_____/     \/_/    \/_/ /_/ \/_____/ \/_/\/_/ \/_____/

                   BHD:   33fKEwAHxVwnrhisREFdSNmZkguo76a2ML
                   BURST: BURST-BVUD-7VWE-HD7F-6RX4P
                   ETH:   0xfEc6F48633A7c557b4ac5c37B4519C55CD701BEF
                   BTC:   14rbdLr2YXDkguVaqRKnPftTPX52tnv2x2

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
    at new Sequelize (/usr/local/lib/node_modules/foxy-proxy/node_modules/sequelize/lib/sequelize.js:340:20)
    at init (/usr/local/lib/node_modules/foxy-proxy/models/index.js:40:21)
    at module.exports (/usr/local/lib/node_modules/foxy-proxy/models/index.js:75:5)
    at /usr/local/lib/node_modules/foxy-proxy/app.js:104:9
    at Object.<anonymous> (/usr/local/lib/node_modules/foxy-proxy/app.js:278:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-08-03 14:50:47.414 [ERROR] | Error: Please install sqlite3 package manually

**Comment by felixbrucker** [comment]
I see you are using root to install packages, which is not recommended. Recommended setup is as your regular user via nvm: https://docs.foxypool.cf/general/installing-nodejs/#linux-mac-os-x

For the insecure root install you'll need `npm install --unsafe-perm -g foxy-proxy`

**Comment by jacobianb** [comment]
After following your guide then attempting to install again as regular user:
```
jake@jake-linuxvm:~/.config/foxy-proxy$ npm install -g foxy-proxy
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/foxy-proxy
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN notsup Unsupported engine for bitmart-api@1.2.0: wanted: {"node":"^12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: bitmart-api@1.2.0

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/foxy-proxy
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/foxy-proxy'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/foxy-proxy']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/foxy-proxy\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/foxy-proxy' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jake/.npm/_logs/2020-08-03T21_31_34_941Z-debug.log

```

**Comment by felixbrucker** [comment]
You seem to be using the system npm/node install, please remove it via `sudo apt remove --purge npm nodejs`

**Comment by jacobianb** [comment]
Seems to be working great now. Thank you. The issue was that npm needed to be installed nvm as a regular user.
